// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQQTAO4Bbi8LdRBCCLGDf0KTWDV4e9un4',
    appId: '1:78416144642:web:b2081bf7f128603c73ba1b',
    messagingSenderId: '78416144642',
    projectId: 'flavor-delight',
    authDomain: 'flavor-delight.firebaseapp.com',
    storageBucket: 'flavor-delight.firebasestorage.app',
    measurementId: 'G-F1J6S6EYSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkiP0ZZyZYKJ9-dCDX3JWTwjAvhM3W7sk',
    appId: '1:78416144642:android:8803ed447869caa173ba1b',
    messagingSenderId: '78416144642',
    projectId: 'flavor-delight',
    storageBucket: 'flavor-delight.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdouHE5RRojQwB_GOtsWTbqlLDZTuX-Fg',
    appId: '1:78416144642:ios:a25c5ae2f7a6a74973ba1b',
    messagingSenderId: '78416144642',
    projectId: 'flavor-delight',
    storageBucket: 'flavor-delight.firebasestorage.app',
    iosBundleId: 'com.sweetrise.WV54Application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdouHE5RRojQwB_GOtsWTbqlLDZTuX-Fg',
    appId: '1:78416144642:ios:b4dbbdc254de053a73ba1b',
    messagingSenderId: '78416144642',
    projectId: 'flavor-delight',
    storageBucket: 'flavor-delight.firebasestorage.app',
    iosBundleId: 'com.example.bakery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQQTAO4Bbi8LdRBCCLGDf0KTWDV4e9un4',
    appId: '1:78416144642:web:db9d59c368b01ca373ba1b',
    messagingSenderId: '78416144642',
    projectId: 'flavor-delight',
    authDomain: 'flavor-delight.firebaseapp.com',
    storageBucket: 'flavor-delight.firebasestorage.app',
    measurementId: 'G-ZGZ3SPR93X',
  );
}
